### ISSUE TITLE
Using Container Lifecycle Hooks vs capturing exit signals for runner removal

### ISSUE THREAD

**Issue by bharathkkb** [github-developer/self-hosted-runners-anthos#2]
Hi @imjohnbo 

I had originally implemented [GKE Self Hosted Runner Deployment](https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/8c5f421d02dc221cf742b4c8e839b1acb32fb04c/examples/gh-runner-gke-dind/sample-manifests/deployment.yaml#L55) with Container Lifecycle Hooks which removes runners when pod exits as opposed to capturing SIGTERM/EXIT signal. I was wondering if one is more advantageous than the other as  Container Lifecycle Hooks seems more k8s native.

Wanted to get your thoughts on this and happy to open a PR

**Comment by imjohnbo** [comment]
Thanks for the link to this @bharathkkb – yes, a PR would be very welcome!

**Comment by imjohnbo** [comment]
One drawback to using Container Lifecycle Hooks is that if you're [running a single Docker container](https://github.com/github-developer/self-hosted-runners-anthos#run-docker-container) it won't exit gracefully, but if you catch the `EXIT` signal it should work on k8s and just in a Docker container.

**Comment by bharathkkb** [comment]
@imjohnbo agreed! For the[ MIG Container VM module](https://github.com/bharathkkb/terraform-google-github-actions-runners/tree/seed-tf-gh-runners/examples/gh-runner-mig-container-vm-dind), I have stuck to capturing EXIT signals. Do we forsee supporting use cases outside of GKE/Anthos with this same Dockerfile?

**Comment by imjohnbo** [comment]
> Do we forsee supporting use cases outside of GKE/Anthos with this same Dockerfile?

No, probably a good idea to keep the focus on Kubernetes. I'll tighten up the README to this effect 🙇
