### ISSUE TITLE
Prebaking Container Image with Runner

### ISSUE THREAD

**Issue by bharathkkb** [github-developer/self-hosted-runners-anthos#4]
hi @imjohnbo 
Got a chance to play around with this today - a couple of questions:

i) Is there a reason why we are not prebaking the runner into the Dockerfile? Runner will also auto update, so even if we bundle an older version, they can get auto updated. Current startup time for this image to become active per pod is 50-60s. I have a [prebaked runner](https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/598a38a72b7bbaf56be431c07de04752c521fd60/examples/gh-runner-gke-dind/Dockerfile) which is less than 5s. 

ii) Do we have plans to support both an official "DIND" and "regular" version of the runner docker image?

**Comment by imjohnbo** [comment]
👋 @bharathkkb

> i) Is there a reason why we are not prebaking the runner into the Dockerfile?

No, I like your approach better! 😄I'd welcome a PR, or I can get to it soon.

> ii) Do we have plans to support both an official "DIND" and "regular" version of the runner docker image?

I'd prefer to move away from DinD [if possible](https://github.com/github-developer/self-hosted-runners-anthos#future-improvements) and support only one runner docker image, but I'm open to your input?

**Comment by imjohnbo** [comment]
> I'd prefer to move away from DinD if possible...

We should keep an eye on whether any replacements to DinD support container features like [`services`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices), [`container`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer). We might be limited to DinD for the time being – in any case, I'd rather support just one runner docker image if possible.
